using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace MoFJsonEditor.Models
{
    public abstract class Loot
    {
        private string _id = null;
        private string _name;
        //we'll make an ID for the items. This will be generated by what type they are
        //i.e. Equipment-HeadPiece-NumberofHeadPiece -> E-H-1
        //Potion-Type(HP/XP)-NumberOfPotions -> P-HP-1
        public string Id
        {
            get
            {
                return _id;
                
            }
            set
            {
                _id = value;
            }
        }
        public string Name
        {
            get { return _name; } 
            set { Id = value;
                _name = value;
            } }
        [JsonConverter(typeof(StringEnumConverter))]
        public LootType Type { get; set; }
        public string ImagePath { get; set; }
        public string SpriteName { get; set; }

    }
}
